feat: add option to configure commit- rules
TomerFi/auto-me-bot pull request #51
Opened 2022-08-02 19:20 UTC by dolby360

Signed-off-by: dolby360 <mrdolbyking@gmail.com>

## Description
Add option to configure commit rules

**Related issue (if any):** fixes #*issue_number_goes_here*

## Checklist

- [v] I have followed this repository's contributing guidelines.
- [v] I have used the conventional commits specification for my commit messages.
- [v] I have signed my commits.
- [v] I will adhere to the project's code of conduct.

2022-08-02 19:53 UTC, TomerFi submitted a review, later dismissed
@dolby360 🔥

2022-08-03 05:55 UTC, TomerFi requested changes

2022-08-03 05:55 UTC, TomerFi commented on .github/auto-me-bot.yml
> +    'body-max-line-length': [2, 'always', 150]
Maybe this should be under the `rules` directive and not directly under the `conventionalCommits` directive?

That way we can keep some kind of correlation to the actual [configuration object](https://commitlint.js.org/#/reference-configuration?id=javascript), so we can perhaps more easily add more configuration values in the future like `parserPreset`, `formatter`, and etc.

https://github.com/TomerFi/auto-me-bot/issues/45#issuecomment-1200277038

2022-08-03 06:19 UTC, TomerFi approved these changes
❤️

2022-08-03 06:25 UTC, merged

2022-08-03 06:43 UTC, TomerFi commented
@all-contributors please add @dolby360 for code and doc

2022-08-03 06:44 UTC, TomerFi commented
@all-contributors please add @dolby360 for code and doc

2022-08-03 06:59 UTC, TomerFi commented
@dolby360 
It's the second time if not more we're collaborating.
you're good - pleasure working with you!

Thank you for your contribution which is included in the new release [1.1.0](https://github.com/TomerFi/auto-me-bot/releases/tag/1.1.0)

2022-08-03 07:32 UTC, dolby360 commented
> @dolby360 It's the second time if not more we're collaborating. you're good - pleasure working with you!
> 
> Thank you for your contribution which is included in the new release [1.1.0](https://github.com/TomerFi/auto-me-bot/releases/tag/1.1.0)

Sure I'm trying to get into open source for a while and your kind approach and responsiveness got me hooked on your projects.